package me.nancex.logophile.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme
val LightPrimary = Color(0xFF4A6741)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFCCEEBD)
val LightOnPrimaryContainer = Color(0xFF082100)
val LightSecondary = Color(0xFF54634D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E8CD)
val LightOnSecondaryContainer = Color(0xFF121F0E)
val LightBackground = Color(0xFFFAFAF5)
val LightOnBackground = Color(0xFF1A1C18)
val LightSurface = Color(0xFFFAFAF5)
val LightOnSurface = Color(0xFF1A1C18)
val LightSurfaceVariant = Color(0xFFDFE4D7)
val LightOnSurfaceVariant = Color(0xFF43483E)

// Dark Theme
val DarkPrimary = Color(0xFFB0D2A3)
val DarkOnPrimary = Color(0xFF1D3717)
val DarkPrimaryContainer = Color(0xFF334F2C)
val DarkOnPrimaryContainer = Color(0xFFCCEEBD)
val DarkSecondary = Color(0xFFBCCCB2)
val DarkOnSecondary = Color(0xFF273421)
val DarkSecondaryContainer = Color(0xFF3D4B37)
val DarkOnSecondaryContainer = Color(0xFFD7E8CD)
val DarkBackground = Color(0xFF1A1C18)
val DarkOnBackground = Color(0xFFE2E3DC)
val DarkSurface = Color(0xFF1A1C18)
val DarkOnSurface = Color(0xFFE2E3DC)
val DarkSurfaceVariant = Color(0xFF43483E)
val DarkOnSurfaceVariant = Color(0xFFC3C8BB)

// Ocean Blue Theme
val OceanPrimary = Color(0xFF3F6090)
val OceanOnPrimary = Color(0xFFFFFFFF)
val OceanPrimaryContainer = Color(0xFFD4E3FF)
val OceanOnPrimaryContainer = Color(0xFF001C3A)
val OceanSecondary = Color(0xFF545F70)
val OceanOnSecondary = Color(0xFFFFFFFF)
val OceanSecondaryContainer = Color(0xFFD8E3F8)
val OceanOnSecondaryContainer = Color(0xFF111C2B)
val OceanBackground = Color(0xFFF8F9FF)
val OceanOnBackground = Color(0xFF191C20)
val OceanSurface = Color(0xFFF8F9FF)
val OceanOnSurface = Color(0xFF191C20)

// Rose Theme
val RosePrimary = Color(0xFF904A4F)
val RoseOnPrimary = Color(0xFFFFFFFF)
val RosePrimaryContainer = Color(0xFFFFDADB)
val RoseOnPrimaryContainer = Color(0xFF3B0811)
val RoseSecondary = Color(0xFF705657)
val RoseOnSecondary = Color(0xFFFFFFFF)
val RoseSecondaryContainer = Color(0xFFFBD9DA)
val RoseOnSecondaryContainer = Color(0xFF271516)
val RoseBackground = Color(0xFFFFF8F7)
val RoseOnBackground = Color(0xFF201A1A)
val RoseSurface = Color(0xFFFFF8F7)
val RoseOnSurface = Color(0xFF201A1A)

// Forest Theme
val ForestPrimary = Color(0xFF3F6944)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestPrimaryContainer = Color(0xFFC0F0C0)
val ForestOnPrimaryContainer = Color(0xFF002106)
val ForestSecondary = Color(0xFF526350)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestSecondaryContainer = Color(0xFFD5E8D1)
val ForestOnSecondaryContainer = Color(0xFF101F10)
val ForestBackground = Color(0xFFF7FBF2)
val ForestOnBackground = Color(0xFF181D17)
val ForestSurface = Color(0xFFF7FBF2)
val ForestOnSurface = Color(0xFF181D17)
